#!/bin/sh
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out
bin/polu.optim.papi.instructions.total >> results/inst_total.tiny.out

bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out
bin/polu.optim.papi.instructions.total >> results/inst_total.small.out

bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out
bin/polu.optim.papi.instructions.total >> results/inst_total.medium.out

bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out
bin/polu.optim.papi.instructions.total >> results/inst_total.big.out

bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out
bin/polu.optim.papi.instructions.total >> results/inst_total.huge.out





bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out
bin/polu.optim.papi.instructions.load >> results/inst_load.tiny.out

bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out
bin/polu.optim.papi.instructions.load >> results/inst_load.small.out

bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out
bin/polu.optim.papi.instructions.load >> results/inst_load.medium.out

bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out
bin/polu.optim.papi.instructions.load >> results/inst_load.big.out

bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out
bin/polu.optim.papi.instructions.load >> results/inst_load.huge.out





bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out
bin/polu.optim.papi.instructions.store >> results/inst_store.tiny.out

bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out
bin/polu.optim.papi.instructions.store >> results/inst_store.small.out

bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out
bin/polu.optim.papi.instructions.store >> results/inst_store.medium.out

bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out
bin/polu.optim.papi.instructions.store >> results/inst_store.big.out

bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out
bin/polu.optim.papi.instructions.store >> results/inst_store.huge.out





bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.tiny.out

bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.small.out

bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.medium.out

bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.big.out

bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
bin/polu.optim.papi.instructions.fp >> results/inst_fp.huge.out
