ROOTD	=	../..

#	Extra dependencies
#	>>	papi.hpp
papi_hpp	=	main

#	Objects Makefile template
TEMPLATE	=	polu.clean.papi.Makefile

include $(ROOTD)/conf/src.papipcc.mk

CXXFLAGS	+=	-DPAPI_MEASURE_L1
