#! /bin/bash
prefix=/home/naps62/projects/pi/fvlib/fv_custom_naps/FVLib
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include
docdir=${prefix}/doc

usage()
{
    cat <<EOF
Usage: FVLib-config [OPTION]

Options:
  --prefix              show FVLib installation prefix 
  --libs                print library linking information
  --cflags              print compiler and pre-processor flags
  --cxx                 c++ compiler
  --cc                  c compiler
  --help                display this help and exit
  --version             output version information

EOF
    exit $1
}

if test $# -eq 0; then
    usage 1 1>&2
fi

cflags=false
includes=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
        prefix=$optarg
        ;;

    --prefix)
        echo $prefix
        ;;

    --exec_prefix)
        echo $exec_prefix
        ;;

    --cxx)
        echo g++
        ;;

    --cc)
        echo gcc
        ;;

    --version)
        echo 2.0.2
        ;;

    --help)
        usage 0
        ;;

    --cflags)
        echo -I ${includedir} -Wall 
        ;;

    --libs)
        echo -L ${libdir} -lFVLib -lm
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done

exit 0

